apiVersion: v1
kind: ConfigMap
metadata:
  name: ticketservice-config
  namespace: ticketservice
data:
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: guest
  SPRING_RABBITMQ_PASSWORD: guest
  SPRING_MAIL_HOST: mailhog
  SPRING_MAIL_PORT: "1025"
  GRPC_INVENTORY_HOST: inventoryservice
  GRPC_INVENTORY_PORT: "9090"
  GRPC_SERVER_PORT: "9090"
  ORDER_SERVICE_URL: http://orderservice:8081
  INVENTORY_SERVICE_URL: http://inventoryservice:8082
  EVENT_SERVICE_URL: http://eventservice:8083
  ORDERSERVICE_URL: http://orderservice:8081
