apiVersion: v1
kind: Secret
metadata:
  name: ticketservice-secrets
  namespace: ticketservice
type: Opaque
stringData:
  mysql-root-password: root
  jwt-secret: ticketservice-dev-secret-must-be-at-least-32-chars-long
