apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  namespace: ticketservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: supersmallservices-userservice:latest
          imagePullPolicy: Never
          ports:
            - name: rest
              containerPort: 8086
            - name: grpc
              containerPort: 9091
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/users_db?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ticketservice-secrets
                  key: mysql-root-password
            - name: GRPC_SERVER_PORT
              value: "9091"
          readinessProbe:
            tcpSocket:
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: userservice
  namespace: ticketservice
spec:
  selector:
    app: userservice
  ports:
    - name: rest
      port: 8086
      targetPort: 8086
    - name: grpc
      port: 9091
      targetPort: 9091
